/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PublicDisplayRouteImport } from './routes/public-display'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminLiveQueueRouteImport } from './routes/admin.live-queue'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientGetTokenRouteImport } from './routes/patient.get-token'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientJoinQueueRouteImport } from './routes/patient.join-queue'
import { Route as PatientLiveQueueRouteImport } from './routes/patient.live-queue'
import { Route as PatientQueueRouteImport } from './routes/patient.queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDisplayRoute = PublicDisplayRouteImport.update({
  id: '/public-display',
  path: '/public-display',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveQueueRoute = AdminLiveQueueRouteImport.update({
  id: '/live-queue',
  path: '/live-queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRoute,
} as any)
const PatientGetTokenRoute = PatientGetTokenRouteImport.update({
  id: '/get-token',
  path: '/get-token',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const PatientJoinQueueRoute = PatientJoinQueueRouteImport.update({
  id: '/join-queue',
  path: '/join-queue',
  getParentRoute: () => PatientRoute,
} as any)
const PatientLiveQueueRoute = PatientLiveQueueRouteImport.update({
  id: '/live-queue',
  path: '/live-queue',
  getParentRoute: () => PatientRoute,
} as any)
const PatientQueueRoute = PatientQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/public-display': typeof PublicDisplayRoute
  '/register': typeof RegisterRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/get-token': typeof PatientGetTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/join-queue': typeof PatientJoinQueueRoute
  '/patient/live-queue': typeof PatientLiveQueueRoute
  '/patient/queue': typeof PatientQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/public-display': typeof PublicDisplayRoute
  '/register': typeof RegisterRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/get-token': typeof PatientGetTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/join-queue': typeof PatientJoinQueueRoute
  '/patient/live-queue': typeof PatientLiveQueueRoute
  '/patient/queue': typeof PatientQueueRoute
  '/admin': typeof AdminIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/public-display': typeof PublicDisplayRoute
  '/register': typeof RegisterRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/get-token': typeof PatientGetTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/join-queue': typeof PatientJoinQueueRoute
  '/patient/live-queue': typeof PatientLiveQueueRoute
  '/patient/queue': typeof PatientQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/patient'
    | '/public-display'
    | '/register'
    | '/admin/history'
    | '/admin/live-queue'
    | '/admin/patients'
    | '/admin/queue'
    | '/admin/settings'
    | '/patient/dashboard'
    | '/patient/get-token'
    | '/patient/history'
    | '/patient/join-queue'
    | '/patient/live-queue'
    | '/patient/queue'
    | '/admin/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/public-display'
    | '/register'
    | '/admin/history'
    | '/admin/live-queue'
    | '/admin/patients'
    | '/admin/queue'
    | '/admin/settings'
    | '/patient/dashboard'
    | '/patient/get-token'
    | '/patient/history'
    | '/patient/join-queue'
    | '/patient/live-queue'
    | '/patient/queue'
    | '/admin'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/patient'
    | '/public-display'
    | '/register'
    | '/admin/history'
    | '/admin/live-queue'
    | '/admin/patients'
    | '/admin/queue'
    | '/admin/settings'
    | '/patient/dashboard'
    | '/patient/get-token'
    | '/patient/history'
    | '/patient/join-queue'
    | '/patient/live-queue'
    | '/patient/queue'
    | '/admin/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  PublicDisplayRoute: typeof PublicDisplayRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-display': {
      id: '/public-display'
      path: '/public-display'
      fullPath: '/public-display'
      preLoaderRoute: typeof PublicDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-queue': {
      id: '/admin/live-queue'
      path: '/live-queue'
      fullPath: '/admin/live-queue'
      preLoaderRoute: typeof AdminLiveQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/get-token': {
      id: '/patient/get-token'
      path: '/get-token'
      fullPath: '/patient/get-token'
      preLoaderRoute: typeof PatientGetTokenRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/join-queue': {
      id: '/patient/join-queue'
      path: '/join-queue'
      fullPath: '/patient/join-queue'
      preLoaderRoute: typeof PatientJoinQueueRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/live-queue': {
      id: '/patient/live-queue'
      path: '/live-queue'
      fullPath: '/patient/live-queue'
      preLoaderRoute: typeof PatientLiveQueueRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/queue': {
      id: '/patient/queue'
      path: '/queue'
      fullPath: '/patient/queue'
      preLoaderRoute: typeof PatientQueueRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminLiveQueueRoute: typeof AdminLiveQueueRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHistoryRoute: AdminHistoryRoute,
  AdminLiveQueueRoute: AdminLiveQueueRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PatientRouteChildren {
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientGetTokenRoute: typeof PatientGetTokenRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientJoinQueueRoute: typeof PatientJoinQueueRoute
  PatientLiveQueueRoute: typeof PatientLiveQueueRoute
  PatientQueueRoute: typeof PatientQueueRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientDashboardRoute: PatientDashboardRoute,
  PatientGetTokenRoute: PatientGetTokenRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientJoinQueueRoute: PatientJoinQueueRoute,
  PatientLiveQueueRoute: PatientLiveQueueRoute,
  PatientQueueRoute: PatientQueueRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  PublicDisplayRoute: PublicDisplayRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
