/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PublicDisplayRouteImport } from './routes/public-display'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminClinicsRouteImport } from './routes/admin.clinics'
import { Route as AdminDataManagementRouteImport } from './routes/admin.data-management'
import { Route as AdminDoctorScheduleRouteImport } from './routes/admin.doctor-schedule'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminFollowUpsRouteImport } from './routes/admin.follow-ups'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminLiveQueueRouteImport } from './routes/admin.live-queue'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as PatientBillingRouteImport } from './routes/patient.billing'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientDocumentsRouteImport } from './routes/patient.documents'
import { Route as PatientGetTokenRouteImport } from './routes/patient.get-token'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientJoinQueueRouteImport } from './routes/patient.join-queue'
import { Route as PatientLiveQueueRouteImport } from './routes/patient.live-queue'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientQueueRouteImport } from './routes/patient.queue'
import { Route as PatientVisitsRouteImport } from './routes/patient.visits'
import { Route as AdminPatientRecordPatientIdRouteImport } from './routes/admin.patient-record.$patientId'
import { Route as AdminVisitsVisitIdRouteImport } from './routes/admin.visits.$visitId'
import { Route as PatientPrescriptionVisitIdRouteImport } from './routes/patient.prescription.$visitId'
import { Route as PatientVisitVisitIdRouteImport } from './routes/patient.visit.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDisplayRoute = PublicDisplayRouteImport.update({
  id: '/public-display',
  path: '/public-display',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataManagementRoute = AdminDataManagementRouteImport.update({
  id: '/data-management',
  path: '/data-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorScheduleRoute = AdminDoctorScheduleRouteImport.update({
  id: '/doctor-schedule',
  path: '/doctor-schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFollowUpsRoute = AdminFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveQueueRoute = AdminLiveQueueRouteImport.update({
  id: '/live-queue',
  path: '/live-queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBillingRoute = PatientBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDocumentsRoute = PatientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PatientRoute,
} as any)
const PatientGetTokenRoute = PatientGetTokenRouteImport.update({
  id: '/get-token',
  path: '/get-token',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const PatientJoinQueueRoute = PatientJoinQueueRouteImport.update({
  id: '/join-queue',
  path: '/join-queue',
  getParentRoute: () => PatientRoute,
} as any)
const PatientLiveQueueRoute = PatientLiveQueueRouteImport.update({
  id: '/live-queue',
  path: '/live-queue',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientQueueRoute = PatientQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => PatientRoute,
} as any)
const PatientVisitsRoute = PatientVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => PatientRoute,
} as any)
const AdminPatientRecordPatientIdRoute =
  AdminPatientRecordPatientIdRouteImport.update({
    id: '/patient-record/$patientId',
    path: '/patient-record/$patientId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminVisitsVisitIdRoute = AdminVisitsVisitIdRouteImport.update({
  id: '/visits/$visitId',
  path: '/visits/$visitId',
  getParentRoute: () => AdminRoute,
} as any)
const PatientPrescriptionVisitIdRoute =
  PatientPrescriptionVisitIdRouteImport.update({
    id: '/prescription/$visitId',
    path: '/prescription/$visitId',
    getParentRoute: () => PatientRoute,
  } as any)
const PatientVisitVisitIdRoute = PatientVisitVisitIdRouteImport.update({
  id: '/visit/$visitId',
  path: '/visit/$visitId',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/public-display': typeof PublicDisplayRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff': typeof StaffRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/doctor-schedule': typeof AdminDoctorScheduleRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/follow-ups': typeof AdminFollowUpsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/get-token': typeof PatientGetTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/join-queue': typeof PatientJoinQueueRoute
  '/patient/live-queue': typeof PatientLiveQueueRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/patient/visits': typeof PatientVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/admin/patient-record/$patientId': typeof AdminPatientRecordPatientIdRoute
  '/admin/visits/$visitId': typeof AdminVisitsVisitIdRoute
  '/patient/prescription/$visitId': typeof PatientPrescriptionVisitIdRoute
  '/patient/visit/$visitId': typeof PatientVisitVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/public-display': typeof PublicDisplayRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff': typeof StaffRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/doctor-schedule': typeof AdminDoctorScheduleRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/follow-ups': typeof AdminFollowUpsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/get-token': typeof PatientGetTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/join-queue': typeof PatientJoinQueueRoute
  '/patient/live-queue': typeof PatientLiveQueueRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/patient/visits': typeof PatientVisitsRoute
  '/admin': typeof AdminIndexRoute
  '/patient': typeof PatientIndexRoute
  '/admin/patient-record/$patientId': typeof AdminPatientRecordPatientIdRoute
  '/admin/visits/$visitId': typeof AdminVisitsVisitIdRoute
  '/patient/prescription/$visitId': typeof PatientPrescriptionVisitIdRoute
  '/patient/visit/$visitId': typeof PatientVisitVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/public-display': typeof PublicDisplayRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff': typeof StaffRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/doctor-schedule': typeof AdminDoctorScheduleRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/follow-ups': typeof AdminFollowUpsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/live-queue': typeof AdminLiveQueueRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/get-token': typeof PatientGetTokenRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/join-queue': typeof PatientJoinQueueRoute
  '/patient/live-queue': typeof PatientLiveQueueRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/patient/visits': typeof PatientVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/admin/patient-record/$patientId': typeof AdminPatientRecordPatientIdRoute
  '/admin/visits/$visitId': typeof AdminVisitsVisitIdRoute
  '/patient/prescription/$visitId': typeof PatientPrescriptionVisitIdRoute
  '/patient/visit/$visitId': typeof PatientVisitVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/patient'
    | '/public-display'
    | '/register'
    | '/reset-password'
    | '/staff'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/branding'
    | '/admin/clinics'
    | '/admin/data-management'
    | '/admin/doctor-schedule'
    | '/admin/documents'
    | '/admin/follow-ups'
    | '/admin/history'
    | '/admin/live-queue'
    | '/admin/patients'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/dashboard'
    | '/patient/documents'
    | '/patient/get-token'
    | '/patient/history'
    | '/patient/join-queue'
    | '/patient/live-queue'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/queue'
    | '/patient/visits'
    | '/admin/'
    | '/patient/'
    | '/admin/patient-record/$patientId'
    | '/admin/visits/$visitId'
    | '/patient/prescription/$visitId'
    | '/patient/visit/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/public-display'
    | '/register'
    | '/reset-password'
    | '/staff'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/branding'
    | '/admin/clinics'
    | '/admin/data-management'
    | '/admin/doctor-schedule'
    | '/admin/documents'
    | '/admin/follow-ups'
    | '/admin/history'
    | '/admin/live-queue'
    | '/admin/patients'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/dashboard'
    | '/patient/documents'
    | '/patient/get-token'
    | '/patient/history'
    | '/patient/join-queue'
    | '/patient/live-queue'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/queue'
    | '/patient/visits'
    | '/admin'
    | '/patient'
    | '/admin/patient-record/$patientId'
    | '/admin/visits/$visitId'
    | '/patient/prescription/$visitId'
    | '/patient/visit/$visitId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/patient'
    | '/public-display'
    | '/register'
    | '/reset-password'
    | '/staff'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/branding'
    | '/admin/clinics'
    | '/admin/data-management'
    | '/admin/doctor-schedule'
    | '/admin/documents'
    | '/admin/follow-ups'
    | '/admin/history'
    | '/admin/live-queue'
    | '/admin/patients'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/patient/appointments'
    | '/patient/billing'
    | '/patient/dashboard'
    | '/patient/documents'
    | '/patient/get-token'
    | '/patient/history'
    | '/patient/join-queue'
    | '/patient/live-queue'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/queue'
    | '/patient/visits'
    | '/admin/'
    | '/patient/'
    | '/admin/patient-record/$patientId'
    | '/admin/visits/$visitId'
    | '/patient/prescription/$visitId'
    | '/patient/visit/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  PublicDisplayRoute: typeof PublicDisplayRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-display': {
      id: '/public-display'
      path: '/public-display'
      fullPath: '/public-display'
      preLoaderRoute: typeof PublicDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-management': {
      id: '/admin/data-management'
      path: '/data-management'
      fullPath: '/admin/data-management'
      preLoaderRoute: typeof AdminDataManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctor-schedule': {
      id: '/admin/doctor-schedule'
      path: '/doctor-schedule'
      fullPath: '/admin/doctor-schedule'
      preLoaderRoute: typeof AdminDoctorScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/follow-ups': {
      id: '/admin/follow-ups'
      path: '/follow-ups'
      fullPath: '/admin/follow-ups'
      preLoaderRoute: typeof AdminFollowUpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-queue': {
      id: '/admin/live-queue'
      path: '/live-queue'
      fullPath: '/admin/live-queue'
      preLoaderRoute: typeof AdminLiveQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/billing': {
      id: '/patient/billing'
      path: '/billing'
      fullPath: '/patient/billing'
      preLoaderRoute: typeof PatientBillingRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/documents': {
      id: '/patient/documents'
      path: '/documents'
      fullPath: '/patient/documents'
      preLoaderRoute: typeof PatientDocumentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/get-token': {
      id: '/patient/get-token'
      path: '/get-token'
      fullPath: '/patient/get-token'
      preLoaderRoute: typeof PatientGetTokenRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/join-queue': {
      id: '/patient/join-queue'
      path: '/join-queue'
      fullPath: '/patient/join-queue'
      preLoaderRoute: typeof PatientJoinQueueRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/live-queue': {
      id: '/patient/live-queue'
      path: '/live-queue'
      fullPath: '/patient/live-queue'
      preLoaderRoute: typeof PatientLiveQueueRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/queue': {
      id: '/patient/queue'
      path: '/queue'
      fullPath: '/patient/queue'
      preLoaderRoute: typeof PatientQueueRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/visits': {
      id: '/patient/visits'
      path: '/visits'
      fullPath: '/patient/visits'
      preLoaderRoute: typeof PatientVisitsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/admin/patient-record/$patientId': {
      id: '/admin/patient-record/$patientId'
      path: '/patient-record/$patientId'
      fullPath: '/admin/patient-record/$patientId'
      preLoaderRoute: typeof AdminPatientRecordPatientIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visits/$visitId': {
      id: '/admin/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/admin/visits/$visitId'
      preLoaderRoute: typeof AdminVisitsVisitIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/prescription/$visitId': {
      id: '/patient/prescription/$visitId'
      path: '/prescription/$visitId'
      fullPath: '/patient/prescription/$visitId'
      preLoaderRoute: typeof PatientPrescriptionVisitIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/visit/$visitId': {
      id: '/patient/visit/$visitId'
      path: '/visit/$visitId'
      fullPath: '/patient/visit/$visitId'
      preLoaderRoute: typeof PatientVisitVisitIdRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminDataManagementRoute: typeof AdminDataManagementRoute
  AdminDoctorScheduleRoute: typeof AdminDoctorScheduleRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFollowUpsRoute: typeof AdminFollowUpsRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminLiveQueueRoute: typeof AdminLiveQueueRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPatientRecordPatientIdRoute: typeof AdminPatientRecordPatientIdRoute
  AdminVisitsVisitIdRoute: typeof AdminVisitsVisitIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminClinicsRoute: AdminClinicsRoute,
  AdminDataManagementRoute: AdminDataManagementRoute,
  AdminDoctorScheduleRoute: AdminDoctorScheduleRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFollowUpsRoute: AdminFollowUpsRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminLiveQueueRoute: AdminLiveQueueRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPatientRecordPatientIdRoute: AdminPatientRecordPatientIdRoute,
  AdminVisitsVisitIdRoute: AdminVisitsVisitIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBillingRoute: typeof PatientBillingRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientDocumentsRoute: typeof PatientDocumentsRoute
  PatientGetTokenRoute: typeof PatientGetTokenRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientJoinQueueRoute: typeof PatientJoinQueueRoute
  PatientLiveQueueRoute: typeof PatientLiveQueueRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientQueueRoute: typeof PatientQueueRoute
  PatientVisitsRoute: typeof PatientVisitsRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientPrescriptionVisitIdRoute: typeof PatientPrescriptionVisitIdRoute
  PatientVisitVisitIdRoute: typeof PatientVisitVisitIdRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBillingRoute: PatientBillingRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientDocumentsRoute: PatientDocumentsRoute,
  PatientGetTokenRoute: PatientGetTokenRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientJoinQueueRoute: PatientJoinQueueRoute,
  PatientLiveQueueRoute: PatientLiveQueueRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientQueueRoute: PatientQueueRoute,
  PatientVisitsRoute: PatientVisitsRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientPrescriptionVisitIdRoute: PatientPrescriptionVisitIdRoute,
  PatientVisitVisitIdRoute: PatientVisitVisitIdRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  PublicDisplayRoute: PublicDisplayRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
